config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index, :edit, :update]
  resources :books
  root 'home#top'
  get 'home/about' => 'home#about'
  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def self.search(method, word)
		if method == "perfect_match"
			Book.where(title: word)
		elsif method == "forward_match"
			Book.where("title LIKE ?", "#{word}%")
		elsif method == "backward_match"
			Book.where("title LIKE ?", "%#{word}")
		elsif method == "partial_match"
			Book.where("title LIKE ?", "%#{word}%")
		end
	end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}

	def self.search(method, word)
		if method == "perfect_match"
			User.where(name: word)
		elsif method == "forward_match"
			User.where("name LIKE ?", "#{word}%")
		elsif method == "backward_match"
			User.where("name LIKE ?", "%#{word}")
		elsif method == "partial_match"
			User.where("name LIKE ?", "%#{word}%")
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
      #sign_upの際にnameのデータ操作を許可。追加したカラム。
    end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		@book = Book.find(params[:book_id])
		@new_book_comment = BookComment.new(book_comment_params)
		@new_book_comment.user_id = current_user.id
		@new_book_comment.book_id = @book.id
		if @new_book_comment.save
			flash[:success] = "Comment was successfully created."
		else
			@book_comments = @book.book_comments
			@user = current_user
			@new_book = Book.new
			render '/books/show'
		end
	end

	def destroy
		comment = BookComment.find(params[:id])
		comment.destroy
		@new_book_comments = BookComment.where(book_id: params[:book_id])
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :ensure_current_user, {only: [:edit]}

  def show
  	@book = Book.find(params[:id])
    @user = @book.user
    @book_comments = @book.book_comments
    @new_book = Book.new
    @new_book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
    @user = current_user
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		  redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
      @user = @book.user
  		render "index"
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def ensure_current_user
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.new(book_id: @book.id)
		favorite.save
	end

	def destroy
		@book = Book.find(params[:book_id])
		favorite = current_user.favorites.find_by(book_id: @book.id)
		favorite.destroy
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		follow = current_user.active_relationships.new(follower_id: params[:user_id])
		follow.save
		redirect_to request.referer
	end

	def destroy
		follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
		follow.destroy
		redirect_to request.referer
	end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		@target = params[:search_target]
		if @target == "User"
			method = params[:search_method]
			word = params[:search_word]
			@users = User.search(method, word)
		elsif @target == "Book"
			method = params[:search_method]
			word = params[:search_word]
			@books = Book.search(method, word)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def edit
  	@user = User.find(params[:id])
    if current_user.id != @user.id
        redirect_to user_path(current_user.id)
    end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render :edit
  	end
  end

  def follows
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$('#list_of_comments').html("<%= j(render 'books/list_of_comments', book_comments: @new_book_comment.book.book_comments) %>");
$('#comment_form').val('')

app/views/book_comments/destroy.js.erb
$('#list_of_comments').html("<%= j(render 'books/list_of_comments', book_comments: @new_book_comments) %>");

app/views/books/_favorites.html.erb
<% if book.favorited_by?(current_user) %>
	<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
		<span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
	<% end %>
<% else %>
	<%= link_to book_favorites_path(book), method: :post, remote: true do %>
		<span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
	<% end %>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user) do %>
					<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
					<% end %>
				</td>
				<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
				<td><%= book.body %></td>
				<td>
					<div id="favorites_buttons">
						<%= render 'books/favorites', book: book %>
					</div>
				</td>
				<td>
					コメント数：<%= book.book_comments.count %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/books/_list_of_comments.html.erb
<% book_comments.each do |book_comment| %>
	<div>
		<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
		<%= book_comment.comment %>
	<% if book_comment.user == current_user %>
		<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment.id), method: :delete, remote: true, class: 'btn btn-danger' %>
	<% end %>
	</div>
<% end %>

app/views/books/_newform.html.erb
<% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_show.html.erb
<table class="table">
	<tr>
		<td>
			<ul style="list-style: none;">
				<li>
					<%= link_to user_path(user) do %>
						<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= user.name %>
					<% end %>
				</li>
			</ul>
		</td>
		<td><%= link_to book.title, book %></td>
		<td><%= book.body %></td>
		<td>
			<div id="favorites_buttons">
				<%= render 'books/favorites', book: book %>
			</div>
		</td>
			<td>
				コメント数：<%= book.book_comments.count %>

				<% if book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn-sm btn-danger destroy_book_#{book.id}"%></td>
        <% end %>
			</td>
	<tr>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<% if @book.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

		      <ul>
		      <% @book.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		<%= form_for(@book) do |f| %>
			<div class="field row">
				<%= f.label :title %>
				<%= f.text_field :title, class: "col-xs-12 book_title" %>
			</div>

			<div class="field row">
				<%= f.label :body %> <!-- ここを変更 -->
				<%= f.text_area :body, class: "col-xs-12 book_body" %>
			</div>

			<div class="actions row">
				<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
			</div>
		<% end %>

		<%= link_to "Show", @book, class: "book_#{@book.id}" %> |
		<%= link_to "Back", books_path, class: "back" %>

	</div>

	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
			<div id="index">
				<%= render 'books/index', books: @books %>
			</div>
		<!--books一覧 -->
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @new_book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<%= render 'books/show', user: @user, book: @book %>

		<div id="list_of_comments">
			<%= render 'books/list_of_comments', book_comments: @book_comments %>
		</div>

			<%= form_with( model:[ @book, @new_book_comment], remote: true) do |f| %>
				<div class="row">
					<div class="col-sm-12">
						<%= f.text_area :comment, id:"comment_form" %>
					</div>
				</div>
						<%= f.submit "送信" %>
			<% end %>

	</div>
</div>

app/views/favorites/create.js.erb
$('#favorites_buttons').html("<%= j(render 'books/favorites', book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons').html("<%= j(render 'books/favorites', book: @book) %>");

app/views/home/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/search/search.html.erb
<% if @target == "User" %>
	<% @users.each do |user| %>
		<h2>Users search for "<%= user.name %>"</h2>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
			</tbody>
		</table>
	<% end %>
<% elsif @target == "Book" %>
	<% @books.each do |book| %>
		<h2>Books search for "<%= book.title %>"</h2>
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>title</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= book.title %></td>
					<td><%= link_to "Show", book, class: "book_#{book.id}" %></td>
				</tr>
			</tbody>
		</table>
	<% end %>
<% end %>

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%=link_to user.active_relationships.count.to_s, user_follows_path(user) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th><%=link_to user.passive_relationships.count.to_s, user_followers_path(user) %></th>
		</tr>
</table>

<div class="row">
	<% if current_user != user %>
		<% if user.followed_by?(current_user) %>
			<p><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %></p>
		<% else %>
			<p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %></p>
		<% end %>
	<% else %>
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	<% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= flash[:notice] %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<div id="error_explanation">
		<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<!-- エラーメッセージ表示-->

<%= form_for(@user) do |f| %>

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.passive_relationships.count %></td>
					<td>フォロワー数：<%= user.active_relationships.count %></td>
					<td>
						<% if current_user != user %>
							<% if user.followed_by?(current_user) %>
								<p><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
							<% else %>
								<p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
							<% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.active_relationships.count %></td>
					<td>フォロワー数：<%= user.passive_relationships.count %></td>
					<td>
						<% if current_user != user %>
							<% if user.followed_by?(current_user) %>
								<p><%=link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></p>
							<% else %>
								<p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
							<% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--users一覧 -->

	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		
		<!--books一覧 -->

	</div>
</div>